name: 'Install VS Components'
description: 'Installs the VS component(s) specified.'
inputs:
  components:  # id of input
    description: 'Component(s) to install, seperated by only a comma.'
    required: true
outputs:
  success:
    description: 'Whether the installation succeeded on all components, true or false.'
runs:
  using: 'node16'
  main: 'index.js'
